export const students = [
  {
    id: 1,
    name: "Samanta William",
    studentId: "#123456789",
    date: "March 25, 2021",
    parent: "Mana William",
    city: "Jakarta",
    grade: "VII C",
    selected: false,
  },
  {
    id: 2,
    name: "Emmanuel Ade",
    studentId: "#123456789",
    date: "March 25, 2021",
    parent: "Ade Ada",
    city: "Jakarta",
    grade: "VII A",
    selected: true,
  },
  {
    id: 3,
    name: "Ajani Honour",
    studentId: "#123456789",
    date: "March 25, 2021",
    parent: "Dekunle Alao",
    city: "Jakarta",
    grade: "VII B",
    selected: true,
  },
  {
    id: 4,
    name: "Samanta William",
    studentId: "#123456789",
    date: "March 25, 2021",
    parent: "Mana William",
    city: "Jakarta",
    grade: "VII C",
    selected: true,
  },
  {
    id: 5,
    name: "Samanta William",
    studentId: "#123456789",
    date: "March 25, 2021",
    parent: "Mana William",
    city: "Jakarta",
    grade: "VII A",
    selected: true,
  },
  {
    id: 6,
    name: "Samanta William",
    studentId: "#123456789",
    date: "March 25, 2021",
    parent: "Mana William",
    city: "Jakarta",
    grade: "VII A",
    selected: true,
  },
  {
    id: 7,
    name: "Samanta William",
    studentId: "#123456789",
    date: "March 25, 2021",
    parent: "Mana William",
    city: "Jakarta",
    grade: "VII A",
    selected: true,
  }
];
